### ISSUE TITLE
"prepush" does not work

### ISSUE THREAD

**Issue by mateatslc** [TobiasTimm/husky-hg#3]
Doesn't trigger my `prepush` npm script (also gave `pre-push` a try to no avail).
The `pre-push` hook I'm trying to trigger with `husky-hg` works fine through hg.
Any idea?

env info: `husky-hg@0.14.3`, `node@8.9.4`, `npm@5.6.0` on macOS v10.13.3

**Comment by mateatslc** [comment]
Looking further, it seems to me that only hooks listed in [hg-hooks.json](https://github.com/TobiasTimm/husky-hg/blob/master/src/hg-hooks.json) are supported, [HOOKS.md](https://github.com/TobiasTimm/husky-hg/blob/master/HOOKS.md) suggests a lot more though. Confused...

**Comment by TobiasTimm** [comment]
yeah i forgot to change that. The documentation was made after I've created the hooks. Will fix that

**Comment by TobiasTimm** [comment]
@mateatslc should work with 0.14.4

**Comment by mateatslc** [comment]
Verified, works! Time to fix was amazing too ;)
